graph TD
    %% Nodes
    query_check[query_check]
    intent_detection[intent_detection]
    intent_branch[intent_branch]
    deep_research_node[deep_research_node]
    banking[banking]
    finance[finance]
    end[end]

    %% Edges
    deep_research_node --> __end__
    intent_detection --> intent_branch
    finance --> __end__
    __start__ --> query_check
    end --> __end__
    query_check --> intent_detection
    banking --> __end__
    intent_branch -->|deep_research| deep_research_node
    intent_branch -->|banking| banking
    intent_branch -->|finance| finance
    intent_branch -->|end| end
